Provde a bashrc with CircleCI helpers

diff --git a/circleci/Dockerfile b/circleci/Dockerfile
--- a/circleci/Dockerfile
+++ b/circleci/Dockerfile
@@ -11,18 +11,23 @@ MAINTAINER Open Data Team
 RUN apt-get update && apt-get install -y --no-install-recommends \
 # CircleCI requirements
     bash openssh-client openssh-server gzip ca-certificates \
-# PahntomJS requirements
+# PhantomJS requirements
     libfontconfig1-dev \
+# Other tools
+    jq \
 # Clean up
     && apt-get autoremove\
     && apt-get clean\
     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
-# We're just setting it to the root user's home (root is default on docker)
-# though you could set it to your' user's home if you need a non-root user
-ENV NVM_DIR /usr/local/nvm
+COPY .bashrc /root/
+
+ENV NVM_DIR /root/.nvm
 ENV NVM_VERSION 0.33.4
+# NVM is failing with -e option
+RUN echo '\n# Failsafe NVM activation\nset +e' >> /root/.bashrc
 RUN curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v${NVM_VERSION}/install.sh | bash
+RUN echo '\nset -e' >> /root/.bashrc
 
 # Upgrade to latest virtualenv version
 RUN pip install -U virtualenv
